### ISSUE TITLE
Not able to run npm install 

### ISSUE THREAD

**Issue by Thavarajan** [Ismaestro/angular-example-app#141]
**Describe the bug**
Nothing fancy
![image](https://user-images.githubusercontent.com/20735810/178314229-3d17460a-4416-4f75-9b27-620de8f65cbe.png)

**Expected behavior**
npm install should run.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 18

**Additional context**
This happens only in node 16, 
node 14 successfully installed

**Comment by Ismaestro** [comment]
Hi @Thavarajan !

That's weird, I have node 16 and npm 8, and no problem at all.

```
ismaestro@MacBook-Pro-Ismael angular-example-app % node -v
v16.13.0
ismaestro@MacBook-Pro-Ismael angular-example-app % npm -v
8.1.0
```

Try this:
```
npm install --force
```

or
```
npm install --legacy-peer-deps
```

**Comment by Thavarajan** [comment]
Both are pointing towards node gyp error while installing node-sass

**Comment by Ismaestro** [comment]
@Thavarajan I've released a new version it should be fixed. Thanks for the report!
