### ISSUE TITLE
Delete a registration

### ISSUE THREAD

**Issue by lisick69** [Ismaestro/angular-example-app#143]
Hi, 

is it possible to delete a registration?

Thanks

**Comment by Ismaestro** [comment]
Hi @lisick69 no it's not possible sorry. If you can develop the feature, you can make a MR to this [repo](https://github.com/Ismaestro/nestjs-example-app).

**Comment by Ismaestro** [comment]
@lisick69 Hi there! I've released a new version where you can delete your account. :)
