### ISSUE TITLE
How to add new components?

### ISSUE THREAD

**Issue by sunch1ld** [Ismaestro/angular-example-app#146]
Hi 

I am trying to add new component in the user module with ng g c command.

Launching this command:

src\app\modules\user\pages> ng g c newcomponent
 
appears this error:

_Could not find an NgModule. Use the '--skip-import' option to skip importing in NgModule._

How can I add new component in page folder using cli command?

Thanks

**Comment by Ismaestro** [comment]
Hello!

As we are not using NgModules anymore, you have to skip the import as it says:
```
ng g c newcomponent --skip-import
```
The component must be standalone, more info here:

https://angular.io/guide/standalone-components

**Comment by sunch1ld** [comment]
Ok thanks work

Dr. Beniamino Ferrari
________________________________
