### ISSUE TITLE
Angular Material

### ISSUE THREAD

**Issue by sunch1ld** [Ismaestro/angular-example-app#147]
Hi I am Beniamino Ferrari,

How can I use angular material components with standalone components in this template?

Best regards

Beniamino Ferrari

**Comment by mindexpert7546** [comment]
There are some step to use the Angular Material into the Standalone Application : 

1. Make sure You have Angular17

2. run this comman > ng add @angular/material 

3. Open the Angular.json file and check angular material style is encluded or not 

4. >go to @node_module>@angular>prebuild_themes>right click theme you want and (copy Relative path> now open the angular.json go to last style array .. it will be near 99-100 line> and paste the copy path 

5. You are done.... whatever material you want to use just import it into your component
