### ISSUE TITLE
Resources not loading

### ISSUE THREAD

**Issue by lucasnahuels** [Ismaestro/angular-example-app#152]
I can't authenticate and the console says resources are not loading. Is the app fly.io down maybe?

**Comment by Ismaestro** [comment]
Hi lucas!

Yup, the node app is down right now, and I’m currently refactoring everthing. Give me a few weeks. You can see the progress under the v18 branch…

**Comment by lucasnahuels** [comment]
oh ok, thanks for your response

**Comment by kpidiba** [comment]
close the issue @lucasnahuels  @Ismaestro

**Comment by Ismaestro** [comment]
Finally, it’s been a month, but the demo is live again! 😊 I’ll keep refining and improving it even more, but the main functionality is back in action.

Feel free to give it a try!
