### ISSUE TITLE
Content Security Policy (CSP) not correct

### ISSUE THREAD

**Issue by danieldanielecki** [Ismaestro/angular-example-app#54]
**Describe the bug**
Content Security Policy is not implemented properly due to many things, e.g. usage of 'unsafe-inline' for CSS & scripts. 

**To Reproduce**
1. Go to https://observatory.mozilla.org/analyze/angularexampleapp.com

**Expected behavior**
Some of the CSP things could be added, examples would include `frameAncestors: ["'self'"],`, removing `"'unsafe-infline'"` from `scriptSrc`, setting `upgradeInsecureRequests: true` for blocking loading of active/passive content over insecure FTP/HTTP.

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any

**Additional context**
Due to Angular's Universal inline CSS rendering we actually can't achieve 100% CSP, so the `"'unsafe-inline'"` for CSS must be there, but others could be improved based on the Mozilla Observatory scan.

**Comment by Ismaestro** [comment]
"Due to Angular's Universal inline CSS rendering we actually can't achieve 100% CSP" Yeah I know... 

let me check the other suggestions, I will inform you. Thanks!
