### ISSUE TITLE
FirebaseError: "Missing or insufficient permissions."

### ISSUE THREAD

**Issue by muldon** [Ismaestro/angular-example-app#80]
Is there something wrong with Firebase ? I just followed the instructions, which is basically pulling the project, installing (npm install) and running ( npm start ), but the app won't load. 

![Screenshot from 2020-06-13 09-36-38](https://user-images.githubusercontent.com/2125312/84568971-87303700-ad59-11ea-83ba-b5460b9b2404.png)

**Comment by Hugoer** [comment]
Hi! i create a new firebase project and modify environment.ts and environment.prod.ts with that project information and it works well. Don´t forget create some data to test it, i create something like that image:
![image](https://user-images.githubusercontent.com/6820634/86273148-1a79c100-bbd0-11ea-9954-0b1244fb72f7.png)
